{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 9,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Requirement already satisfied: gradio in c:\\users\\intel\\anaconda3\\lib\\site-packages (5.34.2)\n",
      "Requirement already satisfied: pymupdf in c:\\users\\intel\\anaconda3\\lib\\site-packages (1.26.1)\n",
      "Requirement already satisfied: faiss-cpu in c:\\users\\intel\\anaconda3\\lib\\site-packages (1.11.0)\n",
      "Requirement already satisfied: sentence-transformers in c:\\users\\intel\\anaconda3\\lib\\site-packages (4.1.0)\n",
      "Requirement already satisfied: transformers in c:\\users\\intel\\anaconda3\\lib\\site-packages (4.52.4)\n",
      "Requirement already satisfied: bertopic in c:\\users\\intel\\anaconda3\\lib\\site-packages (0.17.0)\n",
      "Requirement already satisfied: umap-learn in c:\\users\\intel\\anaconda3\\lib\\site-packages (0.5.7)\n",
      "Requirement already satisfied: hdbscan in c:\\users\\intel\\anaconda3\\lib\\site-packages (0.8.40)\n",
      "Requirement already satisfied: aiofiles<25.0,>=22.0 in c:\\users\\intel\\anaconda3\\lib\\site-packages (from gradio) (24.1.0)\n",
      "Requirement already satisfied: anyio<5.0,>=3.0 in c:\\users\\intel\\anaconda3\\lib\\site-packages (from gradio) (4.2.0)\n",
      "Requirement already satisfied: fastapi<1.0,>=0.115.2 in c:\\users\\intel\\anaconda3\\lib\\site-packages (from gradio) (0.115.13)\n",
      "Requirement already satisfied: ffmpy in c:\\users\\intel\\anaconda3\\lib\\site-packages (from gradio) (0.6.0)\n",
      "Requirement already satisfied: gradio-client==1.10.3 in c:\\users\\intel\\anaconda3\\lib\\site-packages (from gradio) (1.10.3)\n",
      "Requirement already satisfied: groovy~=0.1 in c:\\users\\intel\\anaconda3\\lib\\site-packages (from gradio) (0.1.2)\n",
      "Requirement already satisfied: httpx>=0.24.1 in c:\\users\\intel\\anaconda3\\lib\\site-packages (from gradio) (0.27.0)\n",
      "Requirement already satisfied: huggingface-hub>=0.28.1 in c:\\users\\intel\\anaconda3\\lib\\site-packages (from gradio) (0.33.0)\n",
      "Requirement already satisfied: jinja2<4.0 in c:\\users\\intel\\anaconda3\\lib\\site-packages (from gradio) (3.1.4)\n",
      "Requirement already satisfied: markupsafe<4.0,>=2.0 in c:\\users\\intel\\anaconda3\\lib\\site-packages (from gradio) (2.1.3)\n",
      "Requirement already satisfied: numpy<3.0,>=1.0 in c:\\users\\intel\\anaconda3\\lib\\site-packages (from gradio) (1.26.4)\n",
      "Requirement already satisfied: orjson~=3.0 in c:\\users\\intel\\anaconda3\\lib\\site-packages (from gradio) (3.10.18)\n",
      "Requirement already satisfied: packaging in c:\\users\\intel\\anaconda3\\lib\\site-packages (from gradio) (24.1)\n",
      "Requirement already satisfied: pandas<3.0,>=1.0 in c:\\users\\intel\\anaconda3\\lib\\site-packages (from gradio) (2.2.2)\n",
      "Requirement already satisfied: pillow<12.0,>=8.0 in c:\\users\\intel\\anaconda3\\lib\\site-packages (from gradio) (10.4.0)\n",
      "Requirement already satisfied: pydantic<2.12,>=2.0 in c:\\users\\intel\\anaconda3\\lib\\site-packages (from gradio) (2.8.2)\n",
      "Requirement already satisfied: pydub in c:\\users\\intel\\anaconda3\\lib\\site-packages (from gradio) (0.25.1)\n",
      "Requirement already satisfied: python-multipart>=0.0.18 in c:\\users\\intel\\anaconda3\\lib\\site-packages (from gradio) (0.0.20)\n",
      "Requirement already satisfied: pyyaml<7.0,>=5.0 in c:\\users\\intel\\anaconda3\\lib\\site-packages (from gradio) (6.0.1)\n",
      "Requirement already satisfied: ruff>=0.9.3 in c:\\users\\intel\\anaconda3\\lib\\site-packages (from gradio) (0.12.0)\n",
      "Requirement already satisfied: safehttpx<0.2.0,>=0.1.6 in c:\\users\\intel\\anaconda3\\lib\\site-packages (from gradio) (0.1.6)\n",
      "Requirement already satisfied: semantic-version~=2.0 in c:\\users\\intel\\anaconda3\\lib\\site-packages (from gradio) (2.10.0)\n",
      "Requirement already satisfied: starlette<1.0,>=0.40.0 in c:\\users\\intel\\anaconda3\\lib\\site-packages (from gradio) (0.46.2)\n",
      "Requirement already satisfied: tomlkit<0.14.0,>=0.12.0 in c:\\users\\intel\\anaconda3\\lib\\site-packages (from gradio) (0.13.3)\n",
      "Requirement already satisfied: typer<1.0,>=0.12 in c:\\users\\intel\\anaconda3\\lib\\site-packages (from gradio) (0.16.0)\n",
      "Requirement already satisfied: typing-extensions~=4.0 in c:\\users\\intel\\anaconda3\\lib\\site-packages (from gradio) (4.11.0)\n",
      "Requirement already satisfied: uvicorn>=0.14.0 in c:\\users\\intel\\anaconda3\\lib\\site-packages (from gradio) (0.34.3)\n",
      "Requirement already satisfied: fsspec in c:\\users\\intel\\anaconda3\\lib\\site-packages (from gradio-client==1.10.3->gradio) (2024.6.1)\n",
      "Requirement already satisfied: websockets<16.0,>=10.0 in c:\\users\\intel\\anaconda3\\lib\\site-packages (from gradio-client==1.10.3->gradio) (15.0.1)\n",
      "Requirement already satisfied: tqdm in c:\\users\\intel\\anaconda3\\lib\\site-packages (from sentence-transformers) (4.66.5)\n",
      "Requirement already satisfied: torch>=1.11.0 in c:\\users\\intel\\anaconda3\\lib\\site-packages (from sentence-transformers) (2.7.1)\n",
      "Requirement already satisfied: scikit-learn in c:\\users\\intel\\anaconda3\\lib\\site-packages (from sentence-transformers) (1.5.1)\n",
      "Requirement already satisfied: scipy in c:\\users\\intel\\anaconda3\\lib\\site-packages (from sentence-transformers) (1.13.1)\n",
      "Requirement already satisfied: filelock in c:\\users\\intel\\anaconda3\\lib\\site-packages (from transformers) (3.13.1)\n",
      "Requirement already satisfied: regex!=2019.12.17 in c:\\users\\intel\\anaconda3\\lib\\site-packages (from transformers) (2024.9.11)\n",
      "Requirement already satisfied: requests in c:\\users\\intel\\anaconda3\\lib\\site-packages (from transformers) (2.32.3)\n",
      "Requirement already satisfied: tokenizers<0.22,>=0.21 in c:\\users\\intel\\anaconda3\\lib\\site-packages (from transformers) (0.21.1)\n",
      "Requirement already satisfied: safetensors>=0.4.3 in c:\\users\\intel\\anaconda3\\lib\\site-packages (from transformers) (0.5.3)\n",
      "Requirement already satisfied: plotly>=4.7.0 in c:\\users\\intel\\anaconda3\\lib\\site-packages (from bertopic) (5.24.1)\n",
      "Requirement already satisfied: numba>=0.51.2 in c:\\users\\intel\\anaconda3\\lib\\site-packages (from umap-learn) (0.60.0)\n",
      "Requirement already satisfied: pynndescent>=0.5 in c:\\users\\intel\\anaconda3\\lib\\site-packages (from umap-learn) (0.5.13)\n",
      "Requirement already satisfied: joblib>=1.0 in c:\\users\\intel\\anaconda3\\lib\\site-packages (from hdbscan) (1.4.2)\n",
      "Requirement already satisfied: idna>=2.8 in c:\\users\\intel\\anaconda3\\lib\\site-packages (from anyio<5.0,>=3.0->gradio) (3.7)\n",
      "Requirement already satisfied: sniffio>=1.1 in c:\\users\\intel\\anaconda3\\lib\\site-packages (from anyio<5.0,>=3.0->gradio) (1.3.0)\n",
      "Requirement already satisfied: certifi in c:\\users\\intel\\anaconda3\\lib\\site-packages (from httpx>=0.24.1->gradio) (2025.4.26)\n",
      "Requirement already satisfied: httpcore==1.* in c:\\users\\intel\\anaconda3\\lib\\site-packages (from httpx>=0.24.1->gradio) (1.0.2)\n",
      "Requirement already satisfied: h11<0.15,>=0.13 in c:\\users\\intel\\anaconda3\\lib\\site-packages (from httpcore==1.*->httpx>=0.24.1->gradio) (0.14.0)\n",
      "Requirement already satisfied: llvmlite<0.44,>=0.43.0dev0 in c:\\users\\intel\\anaconda3\\lib\\site-packages (from numba>=0.51.2->umap-learn) (0.43.0)\n",
      "Requirement already satisfied: python-dateutil>=2.8.2 in c:\\users\\intel\\anaconda3\\lib\\site-packages (from pandas<3.0,>=1.0->gradio) (2.9.0.post0)\n",
      "Requirement already satisfied: pytz>=2020.1 in c:\\users\\intel\\anaconda3\\lib\\site-packages (from pandas<3.0,>=1.0->gradio) (2024.1)\n",
      "Requirement already satisfied: tzdata>=2022.7 in c:\\users\\intel\\anaconda3\\lib\\site-packages (from pandas<3.0,>=1.0->gradio) (2023.3)\n",
      "Requirement already satisfied: tenacity>=6.2.0 in c:\\users\\intel\\anaconda3\\lib\\site-packages (from plotly>=4.7.0->bertopic) (8.2.3)\n",
      "Requirement already satisfied: annotated-types>=0.4.0 in c:\\users\\intel\\anaconda3\\lib\\site-packages (from pydantic<2.12,>=2.0->gradio) (0.6.0)\n",
      "Requirement already satisfied: pydantic-core==2.20.1 in c:\\users\\intel\\anaconda3\\lib\\site-packages (from pydantic<2.12,>=2.0->gradio) (2.20.1)\n",
      "Requirement already satisfied: threadpoolctl>=3.1.0 in c:\\users\\intel\\anaconda3\\lib\\site-packages (from scikit-learn->sentence-transformers) (3.5.0)\n",
      "Requirement already satisfied: sympy>=1.13.3 in c:\\users\\intel\\anaconda3\\lib\\site-packages (from torch>=1.11.0->sentence-transformers) (1.14.0)\n",
      "Requirement already satisfied: networkx in c:\\users\\intel\\anaconda3\\lib\\site-packages (from torch>=1.11.0->sentence-transformers) (3.3)\n",
      "Requirement already satisfied: setuptools in c:\\users\\intel\\anaconda3\\lib\\site-packages (from torch>=1.11.0->sentence-transformers) (75.1.0)\n",
      "Requirement already satisfied: colorama in c:\\users\\intel\\anaconda3\\lib\\site-packages (from tqdm->sentence-transformers) (0.4.6)\n",
      "Requirement already satisfied: click>=8.0.0 in c:\\users\\intel\\anaconda3\\lib\\site-packages (from typer<1.0,>=0.12->gradio) (8.1.7)\n",
      "Requirement already satisfied: shellingham>=1.3.0 in c:\\users\\intel\\anaconda3\\lib\\site-packages (from typer<1.0,>=0.12->gradio) (1.5.0)\n",
      "Requirement already satisfied: rich>=10.11.0 in c:\\users\\intel\\anaconda3\\lib\\site-packages (from typer<1.0,>=0.12->gradio) (13.7.1)\n",
      "Requirement already satisfied: charset-normalizer<4,>=2 in c:\\users\\intel\\anaconda3\\lib\\site-packages (from requests->transformers) (3.3.2)\n",
      "Requirement already satisfied: urllib3<3,>=1.21.1 in c:\\users\\intel\\anaconda3\\lib\\site-packages (from requests->transformers) (2.2.3)\n",
      "Requirement already satisfied: six>=1.5 in c:\\users\\intel\\anaconda3\\lib\\site-packages (from python-dateutil>=2.8.2->pandas<3.0,>=1.0->gradio) (1.16.0)\n",
      "Requirement already satisfied: markdown-it-py>=2.2.0 in c:\\users\\intel\\anaconda3\\lib\\site-packages (from rich>=10.11.0->typer<1.0,>=0.12->gradio) (2.2.0)\n",
      "Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\\users\\intel\\anaconda3\\lib\\site-packages (from rich>=10.11.0->typer<1.0,>=0.12->gradio) (2.15.1)\n",
      "Requirement already satisfied: mpmath<1.4,>=1.1.0 in c:\\users\\intel\\anaconda3\\lib\\site-packages (from sympy>=1.13.3->torch>=1.11.0->sentence-transformers) (1.3.0)\n",
      "Requirement already satisfied: mdurl~=0.1 in c:\\users\\intel\\anaconda3\\lib\\site-packages (from markdown-it-py>=2.2.0->rich>=10.11.0->typer<1.0,>=0.12->gradio) (0.1.0)\n"
     ]
    }
   ],
   "source": [
    "# Step 0: Install Dependencies (only once)\n",
    "!pip install gradio pymupdf faiss-cpu sentence-transformers transformers bertopic umap-learn hdbscan"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 15,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Collecting langdetect\n",
      "  Downloading langdetect-1.0.9.tar.gz (981 kB)\n",
      "     ---------------------------------------- 0.0/981.5 kB ? eta -:--:--\n",
      "     ---------- ----------------------------- 262.1/981.5 kB ? eta -:--:--\n",
      "     -------------------------------------- 981.5/981.5 kB 2.7 MB/s eta 0:00:00\n",
      "  Preparing metadata (setup.py): started\n",
      "  Preparing metadata (setup.py): finished with status 'done'\n",
      "Requirement already satisfied: six in c:\\users\\intel\\anaconda3\\lib\\site-packages (from langdetect) (1.16.0)\n",
      "Building wheels for collected packages: langdetect\n",
      "  Building wheel for langdetect (setup.py): started\n",
      "  Building wheel for langdetect (setup.py): finished with status 'done'\n",
      "  Created wheel for langdetect: filename=langdetect-1.0.9-py3-none-any.whl size=993251 sha256=3cb4b3c588d01a8279bab4eef31bade5cf8e454202f902a5ebe01d66239112c3\n",
      "  Stored in directory: c:\\users\\intel\\appdata\\local\\pip\\cache\\wheels\\c1\\67\\88\\e844b5b022812e15a52e4eaa38a1e709e99f06f6639d7e3ba7\n",
      "Successfully built langdetect\n",
      "Installing collected packages: langdetect\n",
      "Successfully installed langdetect-1.0.9\n"
     ]
    }
   ],
   "source": [
    "!pip install langdetect"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 10,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Step 1: Imports & Paths Setup\n",
    "import os\n",
    "import sys\n",
    "import fitz\n",
    "import faiss\n",
    "import numpy as np\n",
    "import pandas as pd\n",
    "import gradio as gr\n",
    "from transformers import pipeline\n",
    "from sentence_transformers import SentenceTransformer\n",
    "from bertopic import BERTopic\n",
    "from transformers import MarianMTModel, MarianTokenizer\n",
    "\n",
    "# Set base directory\n",
    "BASE_DIR = r\"C:\\Users\\intel\\Desktop\\draft RAG\"\n",
    "sys.path.append(os.path.join(BASE_DIR, \"app\"))\n",
    "\n",
    "# Import citation generator\n",
    "from citation_utils import generate_apa_citation"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 11,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Device set to use cpu\n"
     ]
    }
   ],
   "source": [
    "# Step 2: Load FAISS Index, Data & Models\n",
    "# Load CSV\n",
    "df = pd.read_csv(os.path.join(BASE_DIR, \"data\", \"combined_final_papers.csv\")).fillna(\"\")\n",
    "df[\"Combined_Text\"] = df[\"Title\"] + \". \" + df[\"Abstract\"] + \". \" + df[\"Keyword\"]\n",
    "\n",
    "# Load FAISS index\n",
    "index = faiss.read_index(os.path.join(BASE_DIR, \"models\", \"semantic_index.faiss\"))\n",
    "embedding_model = SentenceTransformer(\"all-MiniLM-L6-v2\")\n",
    "summarizer = pipeline(\"summarization\", model=\"facebook/bart-large-cnn\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 20,
   "metadata": {},
   "outputs": [],
   "source": [
    " # Step 3: Core Functions\n",
    "\n",
    "           # 3.1 🧠 Semantic Search\n",
    "def semantic_search(query, top_k=5):\n",
    "    query_embedding = embedding_model.encode([query]).astype(\"float32\")\n",
    "    distances, indices = index.search(query_embedding, top_k)\n",
    "\n",
    "    results = []\n",
    "    for idx in indices[0]:\n",
    "        paper = df.iloc[idx]\n",
    "        citation = generate_apa_citation(paper['Title'], paper['Authors'], paper['Published Date'], paper['PDF Link'])\n",
    "        results.append(f\"📄 **{paper['Title']}**\\n\\n🧑‍🔬 *{paper['Authors']}* | 🗓️ {paper['Published Date']}\\n🔗 [PDF Link]({paper['PDF Link']})\\n\\n🧾 **Citation**: {citation}\\n\\n📝 **Abstract:**\\n{paper['Abstract']}\\n\\n---\")\n",
    "    return \"\\n\\n\".join(results)\n",
    "\n",
    "\n",
    "    # 3.2 📄 PDF + Text Summarizer\n",
    "def chunk_text(text, max_tokens=500):\n",
    "    words = text.split()\n",
    "    return [' '.join(words[i:i+max_tokens]) for i in range(0, len(words), max_tokens)]\n",
    "\n",
    "def summarize_long_text(text):\n",
    "    chunks = chunk_text(text)\n",
    "    summaries = []\n",
    "    for chunk in chunks:\n",
    "        if len(chunk.split()) > 30:\n",
    "            summary = summarizer(chunk, max_length=130, min_length=30, do_sample=False)[0]['summary_text']\n",
    "            summaries.append(summary)\n",
    "    return \"\\n\\n\".join(summaries)\n",
    "\n",
    "def summarize_pdf(pdf):\n",
    "    doc = fitz.open(stream=pdf.read(), filetype=\"pdf\")\n",
    "    text = \"\"\n",
    "    for page in doc:\n",
    "        text += page.get_text()\n",
    "    return summarize_long_text(text)\n",
    "\n",
    "\n",
    "  # 3.3 🌍 Multilingual Search\n",
    "from langdetect import detect\n",
    "\n",
    "def multilingual_search(query, lang):\n",
    "    lang_map = {\n",
    "        \"French\": (\"fr\", \"en\", \"en\", \"fr\"),\n",
    "        \"German\": (\"de\", \"en\", \"en\", \"de\"),\n",
    "        \"Spanish\": (\"es\", \"en\", \"en\", \"es\"),\n",
    "        \"Hindi\": (\"hi\", \"en\", \"en\", \"hi\"),\n",
    "        \"Chinese\": (\"zh\", \"en\", \"en\", \"zh\")\n",
    "    }\n",
    "\n",
    "    if lang not in lang_map:\n",
    "        return \"❌ Language not supported.\"\n",
    "\n",
    "    src, tgt, back_src, back_tgt = lang_map[lang]\n",
    "\n",
    "    model_to_en, tokenizer_to_en = load_translation_model(src, tgt)\n",
    "    model_back, tokenizer_back = load_translation_model(back_src, back_tgt)\n",
    "\n",
    "    translated_query = translate(query, model_to_en, tokenizer_to_en)\n",
    "    english_results = semantic_search(translated_query)\n",
    "    translated_results = translate(english_results, model_back, tokenizer_back)\n",
    "\n",
    "    return translated_results\n",
    "\n",
    "# 3.4 📎 Citation Generator\n",
    "def citation_generator(title, authors, date, pdf_link):\n",
    "    return generate_apa_citation(title, authors, date, pdf_link)\n",
    "\n",
    "# 3.5 📊 Trend Visualization (graph)\n",
    "import matplotlib.pyplot as plt\n",
    "from io import BytesIO\n",
    "from PIL import Image\n",
    "\n",
    "def show_trend_plot():\n",
    "    topic_model = BERTopic.load(os.path.join(BASE_DIR, \"models\", \"bertopic_model\"))\n",
    "    topic_info = topic_model.get_topic_info()\n",
    "    top_topics = topic_info[1:11]  # Skip -1 (outliers)\n",
    "\n",
    "    fig, ax = plt.subplots(figsize=(10, 5))\n",
    "    ax.barh(top_topics['Name'], top_topics['Count'], color='skyblue')\n",
    "    ax.set_xlabel(\"Paper Count\")\n",
    "    ax.set_title(\"Top 10 Research Topics\")\n",
    "    plt.tight_layout()\n",
    "\n",
    "    buf = BytesIO()\n",
    "    plt.savefig(buf, format='png')\n",
    "    buf.seek(0)\n",
    "    return Image.open(buf)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 21,
   "metadata": {
    "scrolled": true
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "* Running on local URL:  http://127.0.0.1:7864\n",
      "* To create a public link, set `share=True` in `launch()`.\n"
     ]
    },
    {
     "data": {
      "text/html": [
       "<div><iframe src=\"http://127.0.0.1:7864/\" width=\"100%\" height=\"500\" allow=\"autoplay; camera; microphone; clipboard-read; clipboard-write;\" frameborder=\"0\" allowfullscreen></iframe></div>"
      ],
      "text/plain": [
       "<IPython.core.display.HTML object>"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "data": {
      "text/plain": []
     },
     "execution_count": 21,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "# Step 4: Gradio Interface\n",
    "import gradio as gr\n",
    "\n",
    "# 🔍 English Search\n",
    "search_interface = gr.Interface(\n",
    "    fn=semantic_search,\n",
    "    inputs=gr.Textbox(label=\"🔍 Enter Research Query (English)\"),\n",
    "    outputs=gr.Markdown(label=\"📄 Top Matching Papers\"),\n",
    "    title=\"📚 Semantic Search\",\n",
    "    description=\"Search academic papers using semantic understanding.\"\n",
    ")\n",
    "\n",
    "# 🌍 Multilingual Search\n",
    "multilingual_interface = gr.Interface(\n",
    "    fn=multilingual_search,\n",
    "    inputs=[\n",
    "        gr.Textbox(label=\"🔍 Enter your query\"),\n",
    "        gr.Dropdown(choices=[\"French\", \"German\", \"Spanish\", \"Hindi\", \"Chinese\"], label=\"🌐 Select Language\")\n",
    "    ],\n",
    "    outputs=gr.Textbox(label=\"📑 Translated Results\"),\n",
    "    title=\"🌍 Multilingual Semantic Search\",\n",
    "    description=\"Enter your research query in a different language. Results will be translated back to your language.\"\n",
    ")\n",
    "\n",
    "# 📄 PDF Summarizer\n",
    "pdf_interface = gr.Interface(\n",
    "    fn=summarize_pdf,\n",
    "    inputs=gr.File(label=\"📄 Upload PDF\"),\n",
    "    outputs=gr.Textbox(label=\"📝 Summary\"),\n",
    "    title=\"🧾 PDF Summarizer\",\n",
    "    description=\"Upload a research PDF to summarize it.\"\n",
    ")\n",
    "\n",
    "# 📝 Long Text Summarizer\n",
    "text_interface = gr.Interface(\n",
    "    fn=summarize_long_text,\n",
    "    inputs=gr.Textbox(lines=15, label=\"📝 Paste Long Text or Abstract\"),\n",
    "    outputs=gr.Textbox(label=\"📌 Summary\"),\n",
    "    title=\"🧠 Text Summarizer\",\n",
    "    description=\"Paste long research text for summarization.\"\n",
    ")\n",
    "\n",
    "# 📎 Citation Generator\n",
    "citation_interface = gr.Interface(\n",
    "    fn=citation_generator,\n",
    "    inputs=[\n",
    "        gr.Textbox(label=\"📘 Title\"),\n",
    "        gr.Textbox(label=\"✍️ Authors (comma-separated)\"),\n",
    "        gr.Textbox(label=\"📅 Published Date (YYYY-MM-DD)\"),\n",
    "        gr.Textbox(label=\"🔗 PDF Link\")\n",
    "    ],\n",
    "    outputs=gr.Textbox(label=\"📎 APA Citation\"),\n",
    "    title=\"🧾 Citation Generator\",\n",
    "    description=\"Auto-generate APA-style citations for your papers.\"\n",
    ")\n",
    "\n",
    "# 📊 Trend Plot\n",
    "trend_interface = gr.Interface(\n",
    "    fn=show_trend_plot,\n",
    "    inputs=[],\n",
    "    outputs=gr.Image(label=\"📊 Topic Trend Graph\"),\n",
    "    title=\"📈 Research Trends\",\n",
    "    description=\"Visualizes the top 10 most common research topics.\"\n",
    ")\n",
    "\n",
    "# 🚀 Launch the complete app\n",
    "gr.TabbedInterface(\n",
    "    [\n",
    "        search_interface,\n",
    "        multilingual_interface,\n",
    "        pdf_interface,\n",
    "        text_interface,\n",
    "        citation_interface,\n",
    "        trend_interface\n",
    "    ],\n",
    "    [\n",
    "        \"🔍 Search\",\n",
    "        \"🌍 Multilingual\",\n",
    "        \"📄 PDF Summarizer\",\n",
    "        \"📝 Text Summarizer\",\n",
    "        \"📎 Citation Generator\",\n",
    "        \"📊 Trend Graph\"\n",
    "    ]\n",
    ").launch()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {
    "id": "zEVZW2H5fqnx"
   },
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "colab": {
   "authorship_tag": "ABX9TyPFE7BCpZwWl5W89MfkikQz",
   "provenance": []
  },
  "kernelspec": {
   "display_name": "Python 3 (base)",
   "language": "python",
   "name": "base"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.7"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}
